# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/fraud/v1/fraud.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/fraud/v1/fraud.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/fraud/v1/fraud.proto\x12\x05\x66raud\"\x8b\x02\n\x12TransactionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x10\n\x08is_fraud\x18\x05 \x01(\x08\x12\x0c\n\x04type\x18\x06 \x01(\t\x12\x18\n\x10old_balance_orig\x18\x07 \x01(\x01\x12\x18\n\x10new_balance_orig\x18\x08 \x01(\x01\x12\x18\n\x10old_balance_dest\x18\t \x01(\x01\x12\x18\n\x10new_balance_dest\x18\n \x01(\x01\x12!\n\x19is_unauthorized_overdraft\x18\x0b \x01(\x01\"5\n\x11IngestionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2X\n\x0e\x46raudIngestion\x12\x46\n\x0fSendTransaction\x12\x19.fraud.TransactionRequest\x1a\x18.fraud.IngestionResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.fraud.v1.fraud_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_TRANSACTIONREQUEST']._serialized_start=38
  _globals['_TRANSACTIONREQUEST']._serialized_end=305
  _globals['_INGESTIONRESPONSE']._serialized_start=307
  _globals['_INGESTIONRESPONSE']._serialized_end=360
  _globals['_FRAUDINGESTION']._serialized_start=362
  _globals['_FRAUDINGESTION']._serialized_end=450
# @@protoc_insertion_point(module_scope)
