// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: proto/fraud/v1/fraud.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TransactionId           string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId                  int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount                  float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp               int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsFraud                 bool                   `protobuf:"varint,5,opt,name=is_fraud,json=isFraud,proto3" json:"is_fraud,omitempty"`
	Type                    string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	OldBalanceOrig          float64                `protobuf:"fixed64,7,opt,name=old_balance_orig,json=oldBalanceOrig,proto3" json:"old_balance_orig,omitempty"`
	NewBalanceOrig          float64                `protobuf:"fixed64,8,opt,name=new_balance_orig,json=newBalanceOrig,proto3" json:"new_balance_orig,omitempty"`
	OldBalanceDest          float64                `protobuf:"fixed64,9,opt,name=old_balance_dest,json=oldBalanceDest,proto3" json:"old_balance_dest,omitempty"`
	NewBalanceDest          float64                `protobuf:"fixed64,10,opt,name=new_balance_dest,json=newBalanceDest,proto3" json:"new_balance_dest,omitempty"`
	IsUnauthorizedOverdraft float64                `protobuf:"fixed64,11,opt,name=is_unauthorized_overdraft,json=isUnauthorizedOverdraft,proto3" json:"is_unauthorized_overdraft,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_proto_fraud_v1_fraud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_v1_fraud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_fraud_v1_fraud_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TransactionRequest) GetIsFraud() bool {
	if x != nil {
		return x.IsFraud
	}
	return false
}

func (x *TransactionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TransactionRequest) GetOldBalanceOrig() float64 {
	if x != nil {
		return x.OldBalanceOrig
	}
	return 0
}

func (x *TransactionRequest) GetNewBalanceOrig() float64 {
	if x != nil {
		return x.NewBalanceOrig
	}
	return 0
}

func (x *TransactionRequest) GetOldBalanceDest() float64 {
	if x != nil {
		return x.OldBalanceDest
	}
	return 0
}

func (x *TransactionRequest) GetNewBalanceDest() float64 {
	if x != nil {
		return x.NewBalanceDest
	}
	return 0
}

func (x *TransactionRequest) GetIsUnauthorizedOverdraft() float64 {
	if x != nil {
		return x.IsUnauthorizedOverdraft
	}
	return 0
}

type IngestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionResponse) Reset() {
	*x = IngestionResponse{}
	mi := &file_proto_fraud_v1_fraud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionResponse) ProtoMessage() {}

func (x *IngestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_v1_fraud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionResponse.ProtoReflect.Descriptor instead.
func (*IngestionResponse) Descriptor() ([]byte, []int) {
	return file_proto_fraud_v1_fraud_proto_rawDescGZIP(), []int{1}
}

func (x *IngestionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_fraud_v1_fraud_proto protoreflect.FileDescriptor

const file_proto_fraud_v1_fraud_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/fraud/v1/fraud.proto\x12\x05fraud\"\x9d\x03\n" +
	"\x12TransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bis_fraud\x18\x05 \x01(\bR\aisFraud\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12(\n" +
	"\x10old_balance_orig\x18\a \x01(\x01R\x0eoldBalanceOrig\x12(\n" +
	"\x10new_balance_orig\x18\b \x01(\x01R\x0enewBalanceOrig\x12(\n" +
	"\x10old_balance_dest\x18\t \x01(\x01R\x0eoldBalanceDest\x12(\n" +
	"\x10new_balance_dest\x18\n" +
	" \x01(\x01R\x0enewBalanceDest\x12:\n" +
	"\x19is_unauthorized_overdraft\x18\v \x01(\x01R\x17isUnauthorizedOverdraft\"G\n" +
	"\x11IngestionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2X\n" +
	"\x0eFraudIngestion\x12F\n" +
	"\x0fSendTransaction\x12\x19.fraud.TransactionRequest\x1a\x18.fraud.IngestionResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_fraud_v1_fraud_proto_rawDescOnce sync.Once
	file_proto_fraud_v1_fraud_proto_rawDescData []byte
)

func file_proto_fraud_v1_fraud_proto_rawDescGZIP() []byte {
	file_proto_fraud_v1_fraud_proto_rawDescOnce.Do(func() {
		file_proto_fraud_v1_fraud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fraud_v1_fraud_proto_rawDesc), len(file_proto_fraud_v1_fraud_proto_rawDesc)))
	})
	return file_proto_fraud_v1_fraud_proto_rawDescData
}

var file_proto_fraud_v1_fraud_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_fraud_v1_fraud_proto_goTypes = []any{
	(*TransactionRequest)(nil), // 0: fraud.TransactionRequest
	(*IngestionResponse)(nil),  // 1: fraud.IngestionResponse
}
var file_proto_fraud_v1_fraud_proto_depIdxs = []int32{
	0, // 0: fraud.FraudIngestion.SendTransaction:input_type -> fraud.TransactionRequest
	1, // 1: fraud.FraudIngestion.SendTransaction:output_type -> fraud.IngestionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_fraud_v1_fraud_proto_init() }
func file_proto_fraud_v1_fraud_proto_init() {
	if File_proto_fraud_v1_fraud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fraud_v1_fraud_proto_rawDesc), len(file_proto_fraud_v1_fraud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fraud_v1_fraud_proto_goTypes,
		DependencyIndexes: file_proto_fraud_v1_fraud_proto_depIdxs,
		MessageInfos:      file_proto_fraud_v1_fraud_proto_msgTypes,
	}.Build()
	File_proto_fraud_v1_fraud_proto = out.File
	file_proto_fraud_v1_fraud_proto_goTypes = nil
	file_proto_fraud_v1_fraud_proto_depIdxs = nil
}
