// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/fraud/v1/fraud.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FraudIngestion_SendTransaction_FullMethodName = "/fraud.FraudIngestion/SendTransaction"
)

// FraudIngestionClient is the client API for FraudIngestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FraudIngestionClient interface {
	SendTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*IngestionResponse, error)
}

type fraudIngestionClient struct {
	cc grpc.ClientConnInterface
}

func NewFraudIngestionClient(cc grpc.ClientConnInterface) FraudIngestionClient {
	return &fraudIngestionClient{cc}
}

func (c *fraudIngestionClient) SendTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*IngestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestionResponse)
	err := c.cc.Invoke(ctx, FraudIngestion_SendTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FraudIngestionServer is the server API for FraudIngestion service.
// All implementations must embed UnimplementedFraudIngestionServer
// for forward compatibility.
type FraudIngestionServer interface {
	SendTransaction(context.Context, *TransactionRequest) (*IngestionResponse, error)
	mustEmbedUnimplementedFraudIngestionServer()
}

// UnimplementedFraudIngestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFraudIngestionServer struct{}

func (UnimplementedFraudIngestionServer) SendTransaction(context.Context, *TransactionRequest) (*IngestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendTransaction not implemented")
}
func (UnimplementedFraudIngestionServer) mustEmbedUnimplementedFraudIngestionServer() {}
func (UnimplementedFraudIngestionServer) testEmbeddedByValue()                        {}

// UnsafeFraudIngestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FraudIngestionServer will
// result in compilation errors.
type UnsafeFraudIngestionServer interface {
	mustEmbedUnimplementedFraudIngestionServer()
}

func RegisterFraudIngestionServer(s grpc.ServiceRegistrar, srv FraudIngestionServer) {
	// If the following call panics, it indicates UnimplementedFraudIngestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FraudIngestion_ServiceDesc, srv)
}

func _FraudIngestion_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudIngestionServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraudIngestion_SendTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudIngestionServer).SendTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FraudIngestion_ServiceDesc is the grpc.ServiceDesc for FraudIngestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FraudIngestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fraud.FraudIngestion",
	HandlerType: (*FraudIngestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendTransaction",
			Handler:    _FraudIngestion_SendTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fraud/v1/fraud.proto",
}
